"""Append new Results subsections + a Discussion stub to brichos-st.docx.

Reads the original docx, removes trailing empty paragraphs, appends
heading + paragraph blocks reflecting the statistical findings, and
writes a side-by-side updated copy. Original is left untouched.
"""
from __future__ import annotations

from copy import deepcopy
from pathlib import Path

import docx
from docx.shared import Pt

SRC = Path("/Users/chrislangseth/Downloads/brichos-st.docx")
DST = Path("/Users/chrislangseth/Downloads/brichos-st_updated.docx")


def add_heading(doc, text: str, style: str = "Heading 2"):
    p = doc.add_paragraph(text, style=style)
    return p


def add_subhead(doc, text: str):
    p = doc.add_paragraph(text, style="normal")
    for run in p.runs:
        run.bold = True
    return p


def add_para(doc, text: str):
    return doc.add_paragraph(text, style="normal")


def main():
    doc = docx.Document(str(SRC))

    # Strip trailing empty paragraphs
    while doc.paragraphs and doc.paragraphs[-1].text.strip() == "":
        p = doc.paragraphs[-1]
        p._element.getparent().remove(p._element)

    # ---- 4th Results subsection -----------------------------------------
    add_subhead(doc,
        "Three orthogonal tests converge on cortical and striatal "
        "BRICHOS-mediated rescue")
    add_para(doc,
        "Because the wild-type cohort included only one mouse, "
        "per-region wild-type-anchored differential expression tests are "
        "structurally invalid. We therefore anchored the disease "
        "signature once at the whole-tissue level (PBS vs WT pseudobulk, "
        "with pooled-variance fallback for the singleton wild-type and "
        "cross-validation against the canonical 52-gene PIG set from "
        "Chen et al., 2020) and tested rescue per region using the "
        "well-powered BRICHOS-vs-PBS contrast (n = 3 vs n = 7 sections).")
    add_para(doc,
        "We applied three orthogonal tests at the regional level. "
        "First, sign concordance — the fraction of disease-signature "
        "genes whose direction reverses under BRICHOS, evaluated by "
        "binomial test against 0.5. Second, a per-mouse Mann-Whitney "
        "test on the fraction of PIG-rescued spots in each section "
        "(spots whose PIG score sits more than 1 SD below the regional "
        "PBS median). Third, an empirical permutation null on the "
        "rescue slope, generated by reshuffling BRICHOS / PBS labels "
        "across the seven non-WT mice (84 unique reassignments).")
    add_para(doc,
        "The three tests converged on the supragranular and "
        "infragranular cortex together with the caudoputamen as the "
        "regions of statistically robust rescue (sign concordance "
        "0.78–0.85, binomial p < 1×10⁻³; per-mouse MWU p = 0.048, 0.024 "
        "and 0.048, respectively; slope permutation p = 0.012 for the "
        "infragranular cortex, at the resolution floor of the test). "
        "Olfactory areas and meninges showed strong direction "
        "concordance but smaller magnitudes, reaching only marginal "
        "permutation significance (p = 0.12). Corpus callosum and "
        "hypothalamus failed all three tests; hippocampus, thalamus "
        "and ventricular area were excluded from inferential testing "
        "because of insufficient PBS replication (≤ 2 sections per "
        "region).")
    add_para(doc,
        "Effect size, expressed as the fraction of the disease "
        "distance recovered (BRI − PBS) / (WT − PBS) at the spot "
        "level, was 8–16 % across responding regions. BRICHOS therefore "
        "acts as a directional modulator of the disease "
        "transcriptional program rather than a full normaliser, "
        "consistent with the partial rescue observed in prior bulk "
        "studies on isolated cortical microglia.")

    # ---- 5th Results subsection -----------------------------------------
    add_subhead(doc,
        "BRICHOS attenuates an interferon-driven microglial-astrocyte "
        "cascade and concurrently restores neuronal signaling activity")
    add_para(doc,
        "To test whether the BRICHOS effect is restricted to "
        "microglia, we scored 21 curated cell-type and pathway "
        "signatures across all rescue-testable regions, and "
        "complemented this with pathway-level GSEA (gseapy prerank, "
        "GO Biological Process 2021) on the per-region BRICHOS-vs-PBS "
        "log-fold-change ranking. Each signature was scored against "
        "its expected disease direction (using the data-driven "
        "PBS-vs-WT signature where available, and a biological prior "
        "otherwise) so that 'rescue' represents the consistent "
        "movement of disease-associated programs back toward "
        "wild-type, and the consistent preservation of homeostatic "
        "programs.")
    add_para(doc,
        "Among the microglial subtypes, the interferon-response "
        "microglia (IRM) program was the most strongly and most "
        "broadly rescued — more so than the canonical PIG, DAM or ARM "
        "modules — across cortex, caudoputamen, meninges, olfactory "
        "areas and even corpus callosum. The hypothalamus was the "
        "single exception, where the IRM signature was instead "
        "exacerbated under BRICHOS treatment.")
    add_para(doc,
        "In parallel, the A1 (neurotoxic) astrocyte signature defined "
        "by Liddelow and colleagues was reduced in the same set of "
        "rescue regions. The disease-associated oligodendrocyte "
        "stress signature (Serpina3n, C4b, Klk6) was attenuated even "
        "more broadly and showed the only white-matter rescue we "
        "observed, with a small but consistent effect in the corpus "
        "callosum. Pan-reactive astrocyte markers were rescued most "
        "strongly in the olfactory areas. These observations are "
        "consistent with a microglia-to-astrocyte induction cascade in "
        "which activated microglia release factors that drive A1 "
        "astrocyte conversion: by dampening the upstream microglial "
        "activation signal, BRICHOS indirectly reduces the downstream "
        "A1 astrocyte and oligodendrocyte-stress responses, extending "
        "the prior cortical-microglia bulk RNA-seq findings into a "
        "multicellular spatial context.")
    add_para(doc,
        "Pathway enrichment recapitulated the same axis at the "
        "molecular level. Genes downregulated by BRICHOS were strongly "
        "enriched for type II interferon (IFN-γ), antiviral and innate "
        "immune response pathways across supragranular cortex (NES = "
        "−2.4, p < 0.001), olfactory areas, infragranular cortex and "
        "meninges. The convergence of IRM-microglia, A1-astrocyte and "
        "IFN-γ pathway readouts identifies type II interferon "
        "signaling as the molecular axis through which BRICHOS acts in "
        "the rescue regions.")
    add_para(doc,
        "Strikingly, the same contrast revealed a complementary "
        "neuronal effect. The plasticity / immediate-early-gene "
        "signature (Arc, Fos, Egr1, Bdnf, Nptx1) was robustly induced "
        "by BRICHOS in cortex, caudoputamen and meninges, and GSEA "
        "of the upregulated half of the ranking returned strong "
        "enrichment for neuropeptide signaling, GPCR signaling "
        "coupled to cyclic nucleotide second messengers, regulated "
        "secretory pathway, calcium-dependent exocytosis and "
        "neurotransmitter receptor regulation in caudoputamen, "
        "infragranular cortex and hypothalamus (NES ≈ +1.9 to +2.2, "
        "p < 0.001). BRICHOS treatment is therefore associated with "
        "restored neuronal signaling activity in the rescue regions, "
        "not only with dampened inflammation.")
    add_para(doc,
        "Several programs were notably not rescued, defining the "
        "boundaries of the BRICHOS transcriptional effect at this "
        "treatment regime. Mature oligodendrocyte transcripts (Mbp, "
        "Mog, Plp1, Cnp, Mag) remained depressed across most regions, "
        "indicating that BRICHOS does not restore myelination at the "
        "transcriptional level. Vascular and barrier programs — "
        "tight-junction components, endothelial and pericyte markers "
        "— were similarly unaffected, suggesting that the meningeal "
        "rescue we observe is unlikely to act through transcriptional "
        "stabilisation of the blood-brain barrier. Heat-shock and "
        "unfolded-protein-response transcripts showed at most modest "
        "modulation, consistent with the established model in which "
        "BRICHOS acts extracellularly on amyloid-β aggregation rather "
        "than through induction of intracellular chaperone networks.")
    add_para(doc,
        "The corpus callosum was discordant. GSEA returned positive "
        "enrichment for inflammatory response, defense response, "
        "neutrophil migration and pattern-recognition-receptor "
        "signaling pathways (NES ≈ +2.0, p < 0.001) — the opposite "
        "direction of the rescue regions. Combined with the wrong-"
        "sign rescue slope and the absence of A1-astrocyte or "
        "microglial rescue at this site, this suggests that BRICHOS "
        "does not benefit white matter at the timescale of treatment "
        "and may transiently increase inflammatory pathway activity "
        "there. The hypothalamus was similarly resistant, consistent "
        "with either a regional ceiling on drug exposure or with the "
        "known transcriptional distinctness of hypothalamic "
        "microglial populations.")

    # ---- Discussion stub ------------------------------------------------
    add_heading(doc, "DISCUSSION", "Heading 2")
    add_para(doc,
        "Our spatial transcriptomic survey establishes four "
        "complementary observations regarding BRICHOS treatment in the "
        "AppNLGF model. First, the disease-associated transcriptional "
        "program — the canonical PIG signature first defined in this "
        "model by Chen et al. — is reproduced at the spatial level "
        "across multiple grey-matter regions. Second, BRICHOS produces "
        "a regionally-restricted, partial rescue of this program: "
        "8–16 % of the disease transcriptional distance is recovered "
        "in cortex, striatum, olfactory areas and meninges, with "
        "supragranular and infragranular cortex and caudoputamen "
        "reaching statistical significance across three orthogonal "
        "tests. Third, the rescue is multicellular and converges on a "
        "single molecular axis — type II interferon signaling — that "
        "drives a microglia-to-astrocyte cascade: BRICHOS dampens "
        "interferon-response microglia (IRM, the most rescued "
        "microglial subtype in our data), reduces downstream A1 "
        "neurotoxic astrocyte induction, and lowers oligodendrocyte "
        "stress markers. Fourth, this immune-attenuating effect is "
        "accompanied by an upregulation of neuronal signaling and "
        "plasticity programs (immediate-early genes, neuropeptide and "
        "GPCR signaling, calcium-dependent exocytosis), suggesting "
        "that BRICHOS preserves or restores neuronal activity in the "
        "rescue regions rather than merely reducing immune-cell load.")
    add_para(doc,
        "Several limitations qualify these conclusions. The single "
        "wild-type animal precludes per-region validation of the "
        "disease signature itself; we mitigate this by anchoring the "
        "signature globally and cross-validating against the "
        "literature PIG set, but a larger wild-type cohort would "
        "permit per-region disease-signature stability testing. "
        "Effect-size estimates for hippocampus, thalamus and "
        "ventricular area are not reported because too few PBS "
        "sections covered these regions; targeted reslicing of the "
        "stored cohort or addition of replicate sections would "
        "address this gap. The white-matter (corpus callosum) result "
        "deserves particular care: pathway enrichment in this region "
        "ran in the opposite direction to the rescue regions, with "
        "positive enrichment for inflammatory and pattern-recognition-"
        "receptor pathways under BRICHOS, indicating that BRICHOS "
        "does not benefit white matter and may transiently increase "
        "inflammatory pathway activity there. Finally, the rescue we "
        "report mixes changes in cell-type composition with per-cell "
        "expression shifts; a deconvolution-stratified analysis "
        "(tangram or equivalent) is the natural next step and will "
        "discriminate whether BRICHOS reduces microglial recruitment, "
        "suppresses per-cell activation, or both.")

    # save
    doc.save(str(DST))
    print(f"wrote {DST}")
    print(f"paragraphs: {len(doc.paragraphs)}")


if __name__ == "__main__":
    main()
